// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulllorfmteeclfvehfxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbGxvcmZtdGVlY2xmdmVoZnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTE0MTksImV4cCI6MjA1NTM4NzQxOX0.TWpWhNBEpPYziVqh74qtM0c5pNpQe5PfrRgNidN_kmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);